# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- Dev

pool:
  vmImage: 'windows-2019'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: CopyFiles@2
  displayName: 'Copy the config file for DEV'
  inputs:
    SourceFolder: $(Agent.BuildDirectory)
    Contents: '**/ConfigDEV.js'
    flattenFolders: true
    TargetFolder: '$(Build.SourcesDirectory)/config'

- task: CopyFiles@2
  displayName: 'Copy the webconfig file for DEV'
  inputs:
    SourceFolder: $(Agent.BuildDirectory)
    Contents: '**/web.config'
    flattenFolders: true
    TargetFolder: '$(Build.SourcesDirectory)'

- task: CmdLine@2
  inputs:
    script: |
      del /f Config.js
      rename ConfigDEV.js Config.js
    workingDirectory: '$(Build.SourcesDirectory)/config'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
  
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
- task: PublishPipelineArtifact@0
  inputs:
    targetPath: '$(System.ArtifactsDirectory)'
